name: Standards Check

on:
  pull_request:
    types: [opened, synchronize]
    branches-ignore:
    - 'dependabot/**'

jobs:
  run-checks:
    runs-on: ubuntu-latest

    steps:
    - uses: uphold/standards-check-action@v1
